### ISSUE TITLE
web ui may require deep change...

### ISSUE THREAD

**Issue by devcurmudgeon** [jacebrowning/doorstop#273]
Reading Jim's [Doorstop Web Interface notes](https://jmacarthur.github.io/doorstop/) he highlights that a multi-user web ui will need ability to serve/handle multiple branches at once. This likely means adding VCS support/coupling (eg for git, via pygit2).

Is this of interest for doorstop?

**Comment by jmacarthur** [comment]
That's not what I meant; you don't need to use git branches to support a multi-user interface. You only need to do that if you want to show different branches in the UI, as Mustard does.

**Comment by devcurmudgeon** [comment]
Oh, sorry. So do you mean that, without any deep coupling changes:
- it will be possible for user1 to work on branch1, and user2 to work on branch2 simultaneously on the same server?
- but user1 won't be able to compare branch1 with branch2, or switch from branch1 to branch2?

**Comment by jmacarthur** [comment]
No, I don't propose that there will be any concept of branches on the editor at all.

**Comment by michaelnt** [comment]
I've started on a web UI to edit documents in the branch [serverjs](https://github.com/jacebrowning/doorstop/tree/feature/serverjs) it needs some more work but we are able to use it now to edit requirements. Each person runs a server locally on their own checkout.

Re the discussion on branches I think you'd need a checkout per user as you shouldn't perform a commit for each edit but rather save the edits to the checkout and then commit a set of changes.

**Comment by devcurmudgeon** [comment]
I agree user needs ability to create a set of changes. And I understand how this can be satisfied by each user running an individual server... but for a large project wouldn't it be better to have one central server?

I'm imagining a situation where doorstop workflow is somehow integrated into Gitlab CI or Travis, for example...

**Comment by michaelnt** [comment]
I think multi user is going to be a lot of work and if you support a changeset/workspace per user using a VCS as the backend you will need the UI to support some way to handle conflicts (on update and commit)

The other option might be a single changeset\workspace shared between users of the web service, perhaps committing to a separate branch, that could be merged using the normal VCS tools. But then you need a way to sync everyone's view of the workspace.

**Comment by jmacarthur** [comment]
My model was based on the git-backed wikis such as ikiwiki. There is no branching there; review is done by adding revert commits, and you do have a commit per edit. This leaves you with an untidy history, but makes the UI much simpler. The wiki model does reviews passively, but since Doorstop already has a active review mechanism built into it, I don't see that as a problem.

**Comment by michaelnt** [comment]
Ok a single shared workspace with a (say 15 minute) write lock when you edit an item and a refresh button to re-load other users edits could work. Would need it to be a single threaded to start with (or would need out of process cache and pipelined VCS operations).

I rebased my branch against HEAD, can we use that as the starting point or stepping stone?

Backend needs
1. Commit method should accept optional username and password argument.
1. Add an authorized method to the vcs backends that returns true if the supplied username and password has permission to commit changes. Or could use a dummy authentication that is just used to capture the username and password and defer the real authentication till commit time.

Frontend/Javascript needs
1. Add normalized and derived attributes and commit log message to edit item dialog
1. Add new item button
1. Display edit button for empty items
1. Add login dialog
1. Add refresh button
1. Tests

**Comment by michaelnt** [comment]
I've implemented 1,2,3 & 5 now.

If you make a change which add a new item or changes the order of items then the javascript re-loads the entire page which makes it a bit slow. I think to avoid that would probably require using a proper javascript toolkit rather than a sprinkling of javascript on top of the existing html.

**Comment by michaelnt** [comment]
I've added basic auth and tried committing (to svn https) on every save and its a bit slow. I keep the dialog open until the commit completes so that you don't loose the edits you've made. Making it more async could help with how slow it is to commit, but you'd need a way to recover the failed edits you were making.

I think we should probably keep the JS out of doorstop for now and just make the backend changes that are required for a JS frontend to work on top of a REST interface.

**Comment by jacebrowning** [comment]
> I think we should probably keep the JS out of doorstop for now and just make the backend changes that are required for a JS frontend to work on top of a REST interface.

I'm a fan of this approach. Feel free to register another package name on PyPI (e.g. `doorstop-web`).

**Comment by jacebrowning** [comment]
I'm going to close this unless anyone thinks there's more to discuss here.
