### ISSUE TITLE
Community chat

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/doorstop#286]
It was mentioned [here](https://github.com/jacebrowning/doorstop/issues/243#issuecomment-285044923) and I've received a few emails about it. Where is the best place to open up a community chat?

I already use Gitter on a few project. I rarely use IRC. Slack seems too heavy for this.

What does everyone else want?

cc @devcurmudgeon @rickeywang @ojohnny @jmacarthur @michaelnt

**Comment by devcurmudgeon** [comment]
Call me an old timer, but i'd say IRC freenode

**Comment by rdc2732** [comment]
If you have a server, rocket chat looks good, never used it.  https://rocket.chat/

**Comment by ojohnny** [comment]
I like the idea of having a community chat, but since I haven't had the time/energy to do any chatting lately I don't really care what is being used.

But for the sake of discussion: One nice property IRC has is that you don't have to create "yet another account w/ user/password credentials" in order to ask one specific question.  However, if you expect all your community users to already have either a Github or Twitter account (and that they are willing to tie those accounts to a community chat), then Gitter might fulfill this property as well. Gitter also appears to have an IRC bridge (irc.gitter.im), so maybe there is some middle ground there?

**Comment by jacebrowning** [comment]
Technically, there is already a Gitter room: https://gitter.im/jacebrowning/doorstop

@devcurmudgeon Would you like to check out the IRC bridge to see if that works for you?

**Comment by devcurmudgeon** [comment]
Sure I'll take a look

**Comment by jacebrowning** [comment]
I'm going to add a Gitter badge to the README.

We can always switch to another form of chat in the future.
